name: CI

on:
  push:
      branches: [main]
  pull_request:
      branches: [main]

permissions:
  contents: read

env:
  RUSTFLAGS: -Dwarnings
  CARGO_TERM_COLOR: always

jobs:
  test-linux:
    name: Test (Ubuntu)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Building
        run: cargo build --verbose --features=boringssl
      - name: Testing (Rust)
        run: cargo test --verbose --features=boringssl
      - name: Linting
        run: cargo clippy --verbose --features=boringssl

  conventional-commits:
      name: Conventional Commits
      runs-on: ubuntu-latest
      timeout-minutes: 15
      steps:
        - uses: actions/checkout@v4
        - uses: webiny/action-conventional-commits@v1.3.0
        
